### ISSUE TITLE
Add Suitcase consumer 

### ISSUE THREAD

**Issue by gwbischof** [bluesky/bluesky-kafka#6]
I think we should add a generic consumer that takes a suitcase, gets the docs from the Kafka partition, and passes them to the suitcase. I think we should also add a script to start the process. This script can be used by Supervisor.

**Comment by gwbischof** [comment]
Something to check, does mongo give an error if the same document is inserted two times? Will this crash the Serializer?  By default the offset commit interval is 5s. If a consumer crashes, after the re-balance, the consumers go back to the last committed offset. This causes documents after the last committed offset to be processed twice.

I see now that a better way to make the Kafka consumer is to subscribe the Serializer to the RemoteDispatcher.

**Comment by gwbischof** [comment]
Whats a good value for auto_offset_reset?

**Comment by gwbischof** [comment]
I think it is nice to have one consumer group per task. The benefit is that if a we add a *.bluesky.documents topic.  This consumer group will automatically start processing the new topic.  Also there are less consumer groups to manage. Each consumer in the group would be able to process documents from any *.bluesky.documents topic.  A challenge with this is that the Suitcase-mongo Serializer gets the database at init, and all operations after are on the same database.

I think that the subscribed methods of the RemoteDispatcher should receive also the topic_name when they receive a message. That way the Serializer knows what database to put the documents in. Then we could subscribe a Serializer Router or Demux to the RemoteDispatcher to send the docs to the correct Serializer.  Maybe this belongs inside of the RemoteDispatcher?

**Comment by gwbischof** [comment]
I imagine the Demux is like a default dict where the default value is a serializer

**Comment by jklynch** [comment]
I think having a single consumer group for all *.bluesky.documents messages could become a performance bottleneck. We can only have 3 partitions per topic since we have 3 brokers, so we can only have 3 consumers in a consumer group. I may be wrong about this but I think we will lose scalability. In the worst case one very active beamline could slow down documents from other beamline. I don't think this is how Kafka consumers are intended to be configured.

**Comment by gwbischof** [comment]
From what I have read. When you have a consumer group that follows multiple topics, each consumer gets a share of the partitions. So if there are 5 topics, each with 3 partitions, there would be a total of 15 partitions. If there are 5 consumers, then each consumer gets 3 partitions from the set of 15.  I don't think we are limited to 3 consumers in the consumer group, we can make as many as we want, I think we may want to have something like 60 consumers in the consumer group, so that each consumer gets one partition. We can spread the consumers over however many machines that we want.

**Comment by jklynch** [comment]
I am happy to look at this idea with some tests. I would like to have a script that would publish fake bluesky documents, like the performance testing scripts you found, so we could see what happens.

**Comment by gwbischof** [comment]
Maybe I can change the Dispatcher to route the documents instead of the LazyMongoRouter, we would also have to add the Serializers in to the Dispatcher if we did this.

**Comment by danielballan** [comment]
> Something to check, does mongo give an error if the same document is inserted two times?

Yes* because we create an unique index on the documents' unique identifiers.

* In practice, this is true for everything except `resource.uid` but for no good reason. Ensure that `resource.uid` is unique in the database like all other uids is high on the list of issues to be addressed by database migrations. See https://github.com/bluesky/suitcase-mongo/pull/26

> Will this crash the Serializer?

Yes, where "crash" means "raises an exception". But it does not render the Serializer unusable, so a specific `DuplicateBlahBlahBlah` exception could be caught and then work could proceed, in principle. (Not sure if that's the right approach here.)
